### ISSUE TITLE
Sort 3 of us - implement algorithm to sort 3 numbers 0,1 & 2

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#1]

**Comment by Mehul-k123** [comment]
Can you assign this to me?

**Comment by VishalGoel11** [comment]
Can you assign it to me ?

**Comment by NiketaSengar** [comment]
Sir please assign me

**Comment by Tanisha1421** [comment]
can u assign it to me?

**Comment by Shashank-Tomar-2004** [comment]
Shashank Tomar
@Frienducation7  can you please assign it to me?

**Comment by Frienducation7** [comment]
assigning the issue to @Mehul-k123 . Go ahead

**Comment by Mehul-k123** [comment]
@Frienducation7  Solved the issue and  created the pull request. Please accept

**Comment by aryasingh258** [comment]
plz assign it to me

**Comment by NiketaSengar** [comment]
pls assign to me

**Comment by Tanisha1421** [comment]
please assign this to me

**Comment by Frienducation7** [comment]
merged
