### ISSUE TITLE
Search an element

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#10]

**Comment by lusifer65** [comment]
#### can you assign to me ?

**Comment by Frienducation7** [comment]
Assignint the issue to @lusifer65 . Go ahead

**Comment by Tanisha1421** [comment]
can u assign it to me?

**Comment by Shashank-Tomar-2004** [comment]
@Frienducation7 Can you please assign it to me?

**Comment by Tanisha1421** [comment]
plz assign it to me

**Comment by Shashank-Tomar-2004** [comment]
Shashank Tomar
@Frienducation7 can you please assign it to me?

**Comment by aryasingh258** [comment]
plz assign it to me

**Comment by Tanisha1421** [comment]
please assign this to me

**Comment by NiketaSengar** [comment]
Pls assign to me

**Comment by vanshikapandey** [comment]
Assigning the issue to @Tanisha1421 . Go ahead

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by vanshikapandey** [comment]
closing as merged
