### ISSUE TITLE
Rotate Matrix by 90 degree

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#11]

**Comment by lusifer65** [comment]
can you assign to me ?
i raised a PR #12 for the please check

**Comment by Frienducation7** [comment]
Thank you for your response 👍...
Will revert you by tomorrow

Team Frienducation

**Comment by Frienducation7** [comment]
Your code changes have been merged @lusifer65 . Thank you for contributing

**Comment by lusifer65** [comment]
### Thank you @Frienducation7

**Comment by Frienducation7** [comment]
Please ping us on whatsapp so that we can add you in our whatsapp community
Contact no 7982152940

Thanks & Regards
Team Frienducation

**Comment by lusifer65** [comment]
ok sure @Frienducation7
