### ISSUE TITLE
Implement Moore's Voting algorithm in Java

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#17]

**Comment by TamannaVerma99** [comment]
Can you please assign this to me? @Frienducation7

**Comment by TamannaVerma99** [comment]
Also I made a pr for moore's algorithm in c++ that I was assigned but that issue got closed and my pr is still not merged can u please check it?

**Comment by Neeleshcode** [comment]
Can you please it to me @Frienducation7

**Comment by Shashank-Tomar-2004** [comment]
Shashank Tomar
@Frienducation7 can you please assign it to me?

**Comment by Frienducation7** [comment]
Merged
