### ISSUE TITLE
Find Maximum Consecutive Ones

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#19]

**Comment by TamannaVerma99** [comment]
Can you please assign this to me? @Frienducation7

**Comment by Frienducation7** [comment]
Assigning it to the @TamannaVerma99

**Comment by TamannaVerma99** [comment]
I have made a pr #26  you can check it.

**Comment by Frienducation7** [comment]
I am unable to see code changes in your pr
Please check

**Comment by Shashank-Tomar-2004** [comment]
Shashank Tomar
@Frienducation7 can you please assign it to me?

**Comment by Tanisha1421** [comment]
please assign this to me

**Comment by Frienducation7** [comment]
merged
