### ISSUE TITLE
Search Element in Grid

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#21]

**Comment by Tanisha1421** [comment]
can u please assign this to me?

**Comment by Frienducation7** [comment]
Assigning issue to @Tanisha1421 . Go ahead

**Comment by aryasingh258** [comment]
plz assign to me

**Comment by Frienducation7** [comment]
Assigning issue to @aryasingh258 .Go ahead

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by vanshikapandey** [comment]
Merged
