### ISSUE TITLE
Implement Kadane's algorithm

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#3]

**Comment by TamannaVerma99** [comment]
@Frienducation7 can you please assign this to me?

**Comment by Frienducation7** [comment]
Thanks for your response 👍

Our team will get back to you soon or you can ping on whatsapp
Contact no - 7982152940

Thanks & Regards
Team Frienducation

**Comment by TamannaVerma99** [comment]
@Frienducation7 I have made a pull request #14 you can check it.

**Comment by aryasingh258** [comment]
Can you assign it to me?

**Comment by Shashank-Tomar-2004** [comment]
@Frienducation7 Can you please assign it to me?

**Comment by Tanisha1421** [comment]
@Frienducation7 can you please assign it to me?

**Comment by Frienducation7** [comment]
merged
