### ISSUE TITLE
Merge Overlapping Intervals

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#39]

**Comment by Neeleshcode** [comment]
I want to commit for this issue. Please assign it to me @Frienducation7 @vanshikapandey

**Comment by NiketaSengar** [comment]
Pls assign me

**Comment by vanshikapandey** [comment]
Assigning the issue to @NiketaSengar . Go ahead

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by vanshikapandey** [comment]
Code changes merged so closing
