### ISSUE TITLE
Complete Maximum Product Subarray

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#40]

**Comment by Neeleshcode** [comment]
I want to commit for this issue. Please assign it to me @Frienducation7 @vanshikapandey

**Comment by vanshikapandey** [comment]
Assigning the issue to @Neeleshcode . Go ahead

**Comment by Neeleshcode** [comment]
I made a pr for Maximum Product Subarray in C++ that I was assigned .... can u please check it?

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by vanshikapandey** [comment]
Closing as merged
