### ISSUE TITLE
Find nth root of a number

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#41]

**Comment by Kinjal2004** [comment]
I want to work on this issue.
I can write C++ code for this.

**Comment by Neeleshcode** [comment]
I want to commit for this issue. Please assign it to me @Frienducation7 @vanshikapandey

**Comment by msravanthi674** [comment]
Please assign it to me @Frienducation7.

**Comment by vanshikapandey** [comment]
Assigning the issue to @Kinjal2004 . Go ahead

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by vanshikapandey** [comment]
Closing as merged
