### ISSUE TITLE
Am I sorted by character frequency

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#43]

**Comment by Neeleshcode** [comment]
Please assign it to me @Frienducation7

**Comment by vanshikapandey** [comment]
Assigning the issue to @Neeleshcode

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by Neeleshcode** [comment]
Sent a pr for this issue assingned to me ...kindly check

**Comment by vanshikapandey** [comment]
Merged
