### ISSUE TITLE
Implement Merge Sort (comments required)

### ISSUE THREAD

**Issue by vanshikapandey** [Frienducation7/AlgoDev#47]

**Comment by aryasingh258** [comment]
plz assign it to me

**Comment by Shashank-Tomar-2004** [comment]
Shashank Tomar 
@Frienducation7 can you please assign it to me?

**Comment by vanshikapandey** [comment]
Assigning the issue to @Shashank-Tomar-2004

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by vanshikapandey** [comment]
closing as merged
