### ISSUE TITLE
Debug 3 sum problem

### ISSUE THREAD

**Issue by vanshikapandey** [Frienducation7/AlgoDev#49]

**Comment by Shashank-Tomar-2004** [comment]
Shashank Tomar
@Frienducation7 can you please assign me this issue?

**Comment by Neeleshcode** [comment]
Neelesh yadav
@Frienducation7 @vanshikapandey can you please assign it to me?

**Comment by aryasingh258** [comment]
Plz assign to me?

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by Tanisha1421** [comment]
please assign this to me

**Comment by vanshikapandey** [comment]
closing as merged
