### ISSUE TITLE
Find Peak Element in the array

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#8]

**Comment by lusifer65** [comment]
### can you assign to me ?

**Comment by aryasingh258** [comment]
Can you assign it to me?

**Comment by Tanisha1421** [comment]
can you assign it to me?

**Comment by Shashank-Tomar-2004** [comment]
@Frienducation7 Can you please assign it to me?

**Comment by Frienducation7** [comment]
assigning the issue to @Shashank-Tomar-2004 . Go ahead

**Comment by Tanisha1421** [comment]
please assign this to me

**Comment by aryasingh258** [comment]
plz assign it to me

**Comment by iNitishSheoran** [comment]
@Frienducation7 can you please assign me this issue?

**Comment by ritul64** [comment]
Please assign it to me.

**Comment by Tanisha1421** [comment]
please assign this issue to me

**Comment by vanshikapandey** [comment]
closing as merged
