### ISSUE TITLE
Print a matrix in spiral

### ISSUE THREAD

**Issue by Frienducation7** [Frienducation7/AlgoDev#9]

**Comment by TamannaVerma99** [comment]
Can you please assign this to me?

**Comment by Frienducation7** [comment]
assigning the issue to @TamannaVerma99 . Go ahead

**Comment by TamannaVerma99** [comment]
@Frienducation7 I have made a pr #16 you can check it.Thanks.

**Comment by Shashank-Tomar-2004** [comment]
Shashank Tomar
@Frienducation7  can you please assign it to me?
